# Generated by Django 4.1.3 on 2022-11-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_author_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='header_img',
            field=models.FileField(null=True, upload_to='images/medias/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('0', 'Other'), ('1', 'Video'), ('2', 'Music'), ('3', 'Podcast'), ('4', 'Image')], default='0', max_length=20),
        ),
    ]
